/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author babu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        //ImageIcon icon = new ImageIcon("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnStaff = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        activeTab = new javax.swing.JLabel();
        btnDishes = new javax.swing.JLabel();
        btnDrinks = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JLabel();
        btnOurstory = new javax.swing.JLabel();
        btnContactus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1075, 684));

        jPanel3.setBackground(new java.awt.Color(255, 217, 151));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(28, 16, 11));

        btnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_staff_normal.png"))); // NOI18N
        btnStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStaffMouseExited(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_home_normal.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        btnDishes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_dishes_normal.png"))); // NOI18N
        btnDishes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDishesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDishesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDishesMouseExited(evt);
            }
        });

        btnDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Drinks_normal.png"))); // NOI18N
        btnDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrinksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrinksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrinksMouseExited(evt);
            }
        });

        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_customers_normal.png"))); // NOI18N
        btnCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersMouseExited(evt);
            }
        });

        btnOurstory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_ourstory_normal.png"))); // NOI18N
        btnOurstory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOurstoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOurstoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOurstoryMouseExited(evt);
            }
        });

        btnContactus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_contactus_normal.png"))); // NOI18N
        btnContactus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContactusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContactusMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(activeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCustomers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(btnDrinks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDishes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOurstory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnContactus, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnStaff)
                .addGap(18, 18, 18)
                .addComponent(btnDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDrinks)
                .addGap(18, 18, 18)
                .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOurstory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContactus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_home_mhover.png"));
        btnHome.setIcon(btnimage);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_home_normal.png"));
        btnHome.setIcon(btnimage);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_home_clicked.png"));
        btnHome.setIcon(btnimage);
        ImageIcon btnimage2 = new ImageIcon(getClass().getResource("/images/home_icon.png"));
        activeTab.setIcon(btnimage2);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseEntered
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_staff_mhover.png"));
        btnStaff.setIcon(btnimage);
    }//GEN-LAST:event_btnStaffMouseEntered

    private void btnStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseClicked
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_staff_clicked.png"));
        btnStaff.setIcon(btnimage);
        ImageIcon btnimage2 = new ImageIcon(getClass().getResource("/images/staff_icon.png"));
        activeTab.setIcon(btnimage2);
    }//GEN-LAST:event_btnStaffMouseClicked

    private void btnStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseExited
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_staff_normal.png"));
        btnStaff.setIcon(btnimage);
    }//GEN-LAST:event_btnStaffMouseExited

    private void btnDishesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDishesMouseEntered
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_dishes_mhover.png"));
        btnDishes.setIcon(btnimage);
    }//GEN-LAST:event_btnDishesMouseEntered

    private void btnDishesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDishesMouseExited
       ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_dishes_normal.png"));
        btnDishes.setIcon(btnimage);
    }//GEN-LAST:event_btnDishesMouseExited

    private void btnDishesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDishesMouseClicked
        ImageIcon btnimage = new ImageIcon(getClass().getResource("/images/btn_dishes_clicked.png"));
        btnDishes.setIcon(btnimage);
        ImageIcon btnimage2 = new ImageIcon(getClass().getResource("/images/dishes_icon.png"));
        activeTab.setIcon(btnimage2);
    }//GEN-LAST:event_btnDishesMouseClicked

    private void btnDrinksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrinksMouseEntered
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_Drinks_mhover.png"));
        btnDrinks.setIcon(btnImage);
    }//GEN-LAST:event_btnDrinksMouseEntered

    private void btnDrinksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrinksMouseExited
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_Drinks_normal.png"));
        btnDrinks.setIcon(btnImage);
    }//GEN-LAST:event_btnDrinksMouseExited

    private void btnDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrinksMouseClicked
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_Drinks_clicked.png"));
        btnDrinks.setIcon(btnImage);
        ImageIcon activeTabicon = new ImageIcon(getClass().getResource("/images/drinks_icon.png"));
        activeTab.setIcon(activeTabicon);
    }//GEN-LAST:event_btnDrinksMouseClicked

    private void btnCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseEntered
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_customers_mhover.png"));
        btnCustomers.setIcon(btnImage);
    }//GEN-LAST:event_btnCustomersMouseEntered

    private void btnCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseExited
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_customers_normal.png"));
        btnCustomers.setIcon(btnImage);
    }//GEN-LAST:event_btnCustomersMouseExited

    private void btnCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseClicked
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_customers_clicked.png"));
        btnCustomers.setIcon(btnImage);
        ImageIcon activeTabicon = new ImageIcon(getClass().getResource("/images/customers_icon.png"));
        activeTab.setIcon(activeTabicon);
    }//GEN-LAST:event_btnCustomersMouseClicked

    private void btnOurstoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOurstoryMouseEntered
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_ourstory_mhover.png"));
        btnOurstory.setIcon(btnImage);
    }//GEN-LAST:event_btnOurstoryMouseEntered

    private void btnOurstoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOurstoryMouseExited
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_ourstory_normal.png"));
        btnOurstory.setIcon(btnImage);
    }//GEN-LAST:event_btnOurstoryMouseExited

    private void btnOurstoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOurstoryMouseClicked
        ImageIcon btnImage = new ImageIcon(getClass().getResource("/images/btn_ourstory_clicked.png"));
        btnOurstory.setIcon(btnImage);
        ImageIcon activeTabicon = new ImageIcon(getClass().getResource("/images/ourstory_icon.png"));
        activeTab.setIcon(activeTabicon);
    }//GEN-LAST:event_btnOurstoryMouseClicked

    private void btnContactusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactusMouseEntered
        ImageIcon btmImage = new ImageIcon(getClass().getResource("/images/btn_contactus_mhover.png"));
        btnContactus.setIcon(btmImage);
    }//GEN-LAST:event_btnContactusMouseEntered

    private void btnContactusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactusMouseExited
        ImageIcon btmImage = new ImageIcon(getClass().getResource("/images/btn_contactus_normal.png"));
        btnContactus.setIcon(btmImage);
    }//GEN-LAST:event_btnContactusMouseExited

    private void btnContactusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactusMouseClicked
        ImageIcon btmImage = new ImageIcon(getClass().getResource("/images/btn_contactus_clicked.png"));
        btnContactus.setIcon(btmImage);
        ImageIcon activeTabicon = new ImageIcon(getClass().getResource("/images/contactus_icon.png"));
        activeTab.setIcon(activeTabicon);
    }//GEN-LAST:event_btnContactusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeTab;
    private javax.swing.JLabel btnContactus;
    private javax.swing.JLabel btnCustomers;
    private javax.swing.JLabel btnDishes;
    private javax.swing.JLabel btnDrinks;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnOurstory;
    private javax.swing.JLabel btnStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
