/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import AppPackage.AnimationClass;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author Muhammad Nasar
 */
public class Home extends javax.swing.JInternalFrame {

    AnimationClass AC = new AnimationClass();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.getContentPane().setBackground(new Color(255, 217, 151));
        setBorder(BorderFactory.createLineBorder(new Color(235, 163, 91)));
        javax.swing.plaf.InternalFrameUI ifu = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);

        SlideShow();
    }

    public void SlideShow() {
        new Thread() {

            int count = 0;

            @Override
            public void run() {
                try {
                    while (true) {
                        switch (count) {
                            case 0:

                                Thread.sleep(3000);

                                AC.jLabelXLeft(0, -1317, 30, 4, jLabel2);
                                AC.jLabelXLeft(1317, 0, 30, 4, jLabel3);

                                
                                count = 1;
                                break;
//                            case 1:
//                                Thread.sleep(3000);
//
//                                AC.jLabelXRight(-1317, 0, 30, 4, jLabel2);
//                                AC.jLabelXRight(0, 1317, 30, 4, jLabel3);
//                                count = 1;
//                                break;
//                                ImageIcon II = new ImageIcon(getClass().getResource("/images/evening_menu.jpg"));
//                                jLabel1.setIcon(II);

//                            case 2:
//                                Thread.sleep(3000);
//
//                                AC.jLabelXRight(-800, 0, 30, 9, jLabel1);
//                                AC.jLabelXRight(0, 800, 30, 9, jLabel2);
//
//                                count = 3;
//                                break;
//                            case 3:
//                                Thread.sleep(3000);
//
//                                AC.jLabelXRight(-800, 0, 30, 9, jLabel1);
//                                AC.jLabelXRight(0, 800, 30, 9, jLabel2);
//                                count = 4;
//                                break;
//                            case 4:
//                                Thread.sleep(3000);
//
//                                AC.jLabelXRight(-800, 0, 30, 9, jLabel1);
//                                AC.jLabelXRight(0, 800, 30, 9, jLabel2);
//                                count = 5;
//                                break;
                        }
                    }
                } catch (Exception e) {

                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 217, 151));
        setBorder(null);
        setTitle("HOME");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_3.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1317, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(1317, 1080));
        jLabel2.setPreferredSize(new java.awt.Dimension(1317, 838));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1317, 838);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_3.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(1317, 838));
        jLabel3.setMinimumSize(new java.awt.Dimension(1317, 838));
        jLabel3.setPreferredSize(new java.awt.Dimension(1317, 838));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1317, 0, 1317, 838);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
