/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.UserDAO;
import entity.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import services.CommonService;
import services.UserService;
import table_models.UserTableModel;

/**
 *
 * @author ibrar
 */
public class UserForm extends javax.swing.JInternalFrame {

    private User user;
    private UserService userService;
    private boolean status;
    private boolean status1;
    private boolean status2;
    private Vector<User> vectorUsers;
    private CommonService commonService;

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
        userService = new UserService();
        commonService = new CommonService();

        this.getContentPane().setBackground(new Color(255, 217, 151));
        setBorder(BorderFactory.createLineBorder(new Color(235, 163, 91)));
        javax.swing.plaf.InternalFrameUI ifu = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);
        vectorUsers = commonService.getVectorUser();
        UserTableModel userTableModel = new UserTableModel(vectorUsers);
        tbluser.setModel(userTableModel);
        tableDesin();

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        chekpas = new javax.swing.JCheckBox();
        txtDisplayName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        txtUpdateDisplayName = new javax.swing.JTextField();
        txtupdatePassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUpdateUserName = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 217, 151));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""))));

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("User Name");
        txtUserName.setToolTipText("User Name");
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });

        chekpas.setText("Show Password");
        chekpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekpasActionPerformed(evt);
            }
        });

        txtDisplayName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDisplayName.setForeground(new java.awt.Color(153, 153, 153));
        txtDisplayName.setText("Display Name");
        txtDisplayName.setToolTipText("Display Name");
        txtDisplayName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisplayNameFocusLost(evt);
            }
        });
        txtDisplayName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisplayNameKeyTyped(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Password");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chekpas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5)
                    .addComponent(txtDisplayName)
                    .addComponent(txtUserName)
                    .addComponent(txtPassword)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chekpas)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbluser.setRowHeight(20);
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbluser);

        jPanel2.setBackground(new java.awt.Color(255, 217, 151));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtUpdateDisplayName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUpdateDisplayName.setForeground(new java.awt.Color(153, 153, 153));
        txtUpdateDisplayName.setText("Update Display Name");
        txtUpdateDisplayName.setToolTipText("Update Display Name");

        txtupdatePassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtupdatePassword.setForeground(new java.awt.Color(153, 153, 153));
        txtupdatePassword.setText("Update Password");
        txtupdatePassword.setToolTipText("Update Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        txtUpdateUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUpdateUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUpdateUserName.setText("Update User name");
        txtUpdateUserName.setToolTipText("Update User name");
        txtUpdateUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateUserNameActionPerformed(evt);
            }
        });

        lblId.setBackground(new java.awt.Color(255, 217, 151));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(txtUpdateUserName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdateDisplayName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtupdatePassword)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUpdateDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUpdateUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtupdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String displayName = txtDisplayName.getText().trim();
        String userName = txtUserName.getText().trim();
        String password = txtPassword.getText().trim();
        user = new User();

        user.setDisplayName(displayName);
        user.setUserName(userName);
        user.setPassword(password);
        int rowAffacted = 0;

        rowAffacted = userService.registerUser(user);

       
            txtDisplayName.setText("Display Name");
            txtDisplayName.setForeground(Color.gray);
            txtUserName.setText("User Name");
            txtUserName.setForeground(Color.gray);
            txtPassword.setText("Password");
            txtPassword.setForeground(Color.gray);
        
        vectorUsers = commonService.getVectorUser();
        UserTableModel userTableModel = new UserTableModel(vectorUsers);
        tbluser.setModel(userTableModel);


    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDisplayNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayNameKeyTyped
        if (status == false) {
            txtDisplayName.setText("");
            // txtDisplayName.setForeground(Color.black);
            status = true;
        }
        txtDisplayName.setForeground(Color.black);
    }//GEN-LAST:event_txtDisplayNameKeyTyped

    private void txtDisplayNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisplayNameFocusLost
        if (txtDisplayName.getText().equals("")) {
            txtDisplayName.setText("Display Name");
            txtDisplayName.setForeground(Color.gray);
            status = false;
        }
    }//GEN-LAST:event_txtDisplayNameFocusLost

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        if (txtUserName.getText().equals("")) {
            txtUserName.setText("User Name");
            txtUserName.setForeground(Color.gray);
            status1 = false;
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        if (status1 == false) {
            txtUserName.setText("");

            status1 = true;
        }
        txtUserName.setForeground(Color.black);
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals("")) {
            txtPassword.setText("Password");
            txtPassword.setForeground(Color.gray);
            status2 = false;
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        if (status2 == false) {
            txtPassword.setText("");

            status2 = true;
        }
        txtPassword.setForeground(Color.black);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void chekpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekpasActionPerformed
        if (evt.getSource() == chekpas) {
            if (chekpas.isSelected()) {
                txtPassword.setEchoChar((char) 0);
            } else {
                txtPassword.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_chekpasActionPerformed

    private void tbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseClicked
        int rowIndex = tbluser.getSelectedRow();
        int choce = JOptionPane.showConfirmDialog(null, "Are You Sure To Update This User Detail?");
        if (choce == 0) {
            UserTableModel userTableModel = (UserTableModel) tbluser.getModel();
            lblId.setText(userTableModel.getValueAt(rowIndex, 0).toString());
            txtUpdateDisplayName.setText(userTableModel.getValueAt(rowIndex, 1).toString());
            txtUpdateUserName.setText(userTableModel.getValueAt(rowIndex, 2).toString());
          //  Object object = tbluser.getSelectionModel();
           // vectorUsers=(Vector<User>) object;
          // User p= vectorUsers.get(4);
          // txtupdatePassword.setText(p.getPassword());
            txtupdatePassword.setText(userTableModel.getValueAt(rowIndex, 3).toString());
            txtUpdateUserName.setForeground(Color.black);
            txtupdatePassword.setForeground(Color.black);
            txtUpdateDisplayName.setForeground(Color.black);
            //  txtUpdateDisplayName.setForeground(Color.black);

        }

    }//GEN-LAST:event_tbluserMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id = lblId.getText();
        String displayName = txtUpdateDisplayName.getText().trim();
        String userName = txtUpdateUserName.getText().trim();
        String password = txtupdatePassword.getText().trim();
        
        User user = new User();
        try{
        user.setUserId(Integer.parseInt(id));
        user.setDisplayName(displayName);
        user.setUserName(userName);
        user.setPassword(password);
        
        userService.updateUser(user);
        
        vectorUsers = commonService.getVectorUser();
        UserTableModel userTableModel = new UserTableModel(vectorUsers);
        tbluser.setModel(userTableModel);
        
        txtUpdateDisplayName.setText("Update Display Name");
        txtUpdateDisplayName.setForeground(Color.gray);

        txtUpdateUserName.setText("Update User name");
        txtUpdateUserName.setForeground(Color.gray);

        txtupdatePassword.setText("Update Password");
        txtupdatePassword.setForeground(Color.gray);
        }catch(Exception E){
            JOptionPane.showMessageDialog(lblId, " Empty  Data Can't Update Please Select data in Table");
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtUpdateUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateUserNameActionPerformed

    
    public void tableDesin(){
        JTableHeader header = tbluser.getTableHeader();
        header.setPreferredSize(new Dimension(150, 50));
        //  header.setBorder(new DropShadowBorder());
        header.setBounds(20, 20, 30, 30);
        header.setFont(new Font("Tahoma", Font.BOLD, 15));
        header.setBackground(Color.red);

        tbluser.setBackground(Color.red);
        ((DefaultTableCellRenderer) tbluser.getDefaultRenderer(Object.class)).setBackground(new Color(255, 255, 204));

        tbluser.setGridColor(Color.red);
        tbluser.setForeground(Color.black);
        jScrollPane1.setBackground(Color.red);
        tbluser.setOpaque(false);
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tbluser.setFont(new Font("Tahome", Font.PLAIN, 20));

        jScrollPane1.getViewport().setOpaque(false);
        tbluser.setShowGrid(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chekpas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtDisplayName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUpdateDisplayName;
    private javax.swing.JTextField txtUpdateUserName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtupdatePassword;
    // End of variables declaration//GEN-END:variables
}
