/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.UserDAO;
import entity.User;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import services.UserService;

/**
 *
 * @author ibrar
 */
public class UserForm extends javax.swing.JInternalFrame {

    private User user;
    private UserService userService;
    private boolean status;
    private boolean status1;
    private boolean status2;
    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
        userService=new UserService();
        
          this.getContentPane().setBackground(new Color(255, 217, 151));
        setBorder(BorderFactory.createLineBorder(new Color(235, 163, 91)));
        javax.swing.plaf.InternalFrameUI ifu = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        chekpas = new javax.swing.JCheckBox();
        txtDisplayName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 217, 151));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""))));

        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("User Name");
        txtUserName.setToolTipText("User Name");
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });

        chekpas.setText("Show Password");
        chekpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekpasActionPerformed(evt);
            }
        });

        txtDisplayName.setForeground(new java.awt.Color(153, 153, 153));
        txtDisplayName.setText("Display Name");
        txtDisplayName.setToolTipText("Display Name");
        txtDisplayName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisplayNameFocusLost(evt);
            }
        });
        txtDisplayName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisplayNameKeyTyped(evt);
            }
        });

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Passworde");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chekpas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chekpas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(84, 130, 135, 52);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String displayName = txtDisplayName.getText().trim();
        String userName = txtUserName.getText().trim();
        String password = txtPassword.getText().trim();
        user=new User();
       
        user.setDisplayName(displayName);
        user.setUserName(userName);
        user.setPassword(password);
        int rowAffacted=0;
        
        rowAffacted=userService.registerUser(user);
        txtDisplayName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        if(rowAffacted==0){
            JOptionPane.showMessageDialog(this, "  Data Not insearted.");
        }else{
            JOptionPane.showMessageDialog(null, "New menu item saved successfully!");
        }
        
        
        


    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDisplayNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisplayNameKeyTyped
     if(status==false){
         txtDisplayName.setText("");
        // txtDisplayName.setForeground(Color.black);
         status=true;
     }txtDisplayName.setForeground(Color.black);
    }//GEN-LAST:event_txtDisplayNameKeyTyped

    private void txtDisplayNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisplayNameFocusLost
         if(txtDisplayName.getText().equals("")){
           txtDisplayName.setText("Display Name");
           txtDisplayName.setForeground(Color.gray);
           status=false;
       }
    }//GEN-LAST:event_txtDisplayNameFocusLost

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
         if(txtUserName.getText().equals("")){
           txtUserName.setText("User Name");
           txtUserName.setForeground(Color.gray);
           status1=false;
       }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
         if(status1==false){
         txtUserName.setText("");
        
         status1=true;
     }txtUserName.setForeground(Color.black);
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
         if(txtPassword.getText().equals("")){
           txtPassword.setText("Password");
           txtPassword.setForeground(Color.gray);
           status2=false;
       }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        if(status2==false){
         txtPassword.setText("");
        
         status2=true;
     }txtPassword.setForeground(Color.black);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void chekpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekpasActionPerformed
       if (evt.getSource() == chekpas) {
            if (chekpas.isSelected()) {
                txtPassword.setEchoChar((char) 0);
            } else {
                txtPassword.setEchoChar('*');
            }}
    }//GEN-LAST:event_chekpasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chekpas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDisplayName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
