package views;

import entity.Waiters;
import java.awt.Color;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import services.CommonService;
import services.WaitersServices;
import table_models.WaitersTableModel;

public class WaitersFormNew extends javax.swing.JInternalFrame {

    private Waiters waiters;
    private CommonService commonService;
    private Vector<Waiters> vectorWaiter;
    private WaitersServices waiterService;
    private boolean status;

    public WaitersFormNew() {
        initComponents();

        this.getContentPane().setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(new Color(201, 201, 201)));
        javax.swing.plaf.InternalFrameUI ifu = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ifu).setNorthPane(null);

        commonService = new CommonService();

        vectorWaiter = commonService.getVectorWaiters();

        waiterService = new WaitersServices();

        WaitersTableModel waiterTableModel = new WaitersTableModel(vectorWaiter);
        tbleWaiter.setModel(waiterTableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtWaiterName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtWaiterNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        txtCnic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbleWaiter = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 217, 151));

        txtWaiterName.setForeground(new java.awt.Color(204, 204, 204));
        txtWaiterName.setText("waiter name");
        txtWaiterName.setToolTipText("waiter name");
        txtWaiterName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWaiterNameFocusLost(evt);
            }
        });
        txtWaiterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaiterNameActionPerformed(evt);
            }
        });
        txtWaiterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWaiterNameKeyTyped(evt);
            }
        });

        jLabel1.setText("Waiter Name");

        jLabel2.setText("Father Name");

        jLabel4.setText("Phone Number");

        jLabel3.setText("Waiter Number");

        txtWaiterNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtWaiterNumber.setText("Waiter Number");
        txtWaiterNumber.setToolTipText("Waiter Number");
        txtWaiterNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWaiterNumberFocusLost(evt);
            }
        });
        txtWaiterNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaiterNumberActionPerformed(evt);
            }
        });
        txtWaiterNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWaiterNumberKeyTyped(evt);
            }
        });

        txtAddress.setForeground(new java.awt.Color(204, 204, 204));
        txtAddress.setText("Address");
        txtAddress.setToolTipText("Address");
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });

        jLabel6.setText("Address");

        txtFatherName.setForeground(new java.awt.Color(204, 204, 204));
        txtFatherName.setText("Father name");
        txtFatherName.setToolTipText("Father name");
        txtFatherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFatherNameFocusLost(evt);
            }
        });
        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });
        txtFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFatherNameKeyTyped(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtPhoneNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtPhoneNumber.setText("Phone Number");
        txtPhoneNumber.setToolTipText("Phone Number");
        txtPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneNumberFocusLost(evt);
            }
        });
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtCnic.setForeground(new java.awt.Color(204, 204, 204));
        txtCnic.setText("Cnic");
        txtCnic.setToolTipText("Cnic");
        txtCnic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnicFocusLost(evt);
            }
        });
        txtCnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnicActionPerformed(evt);
            }
        });
        txtCnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCnicKeyTyped(evt);
            }
        });

        jLabel5.setText("Cnic");

        tbleWaiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbleWaiter);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtWaiterNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtWaiterName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCnic))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWaiterName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWaiterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnicActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (txtWaiterName.getText().equals("") || txtFatherName.getText().equals("")
                || txtWaiterNumber.getText().equals("") || txtPhoneNumber.getText().equals("")
                || txtCnic.getText().equals("") || txtAddress.getText().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "empty data can not be inserted");
            JOptionPane.showMessageDialog(rootPane, "please insert data");

        } else {
            waiters = new Waiters();

            waiters.setName(txtWaiterName.getText());
            waiters.setFatherName(txtFatherName.getText());
            waiters.setWaiterNumber(txtWaiterNumber.getText());
            waiters.setPhoneNumber(Integer.parseInt(txtPhoneNumber.getText()));
            waiters.setCnic(txtCnic.getText());
            waiters.setAddress(txtAddress.getText());

            waiterService.waiter(waiters);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtWaiterNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaiterNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaiterNumberActionPerformed

    private void txtWaiterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaiterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaiterNameActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtWaiterNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaiterNameKeyTyped

        if (status == false) {
            txtWaiterName.setText("");
            status = true;
        }
        txtWaiterName.setForeground(Color.black);

    }//GEN-LAST:event_txtWaiterNameKeyTyped

    private void txtFatherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatherNameKeyTyped

        if (status == false) {
            txtFatherName.setText("");
            status = true;
        }
        txtFatherName.setForeground(Color.black);

    }//GEN-LAST:event_txtFatherNameKeyTyped

    private void txtWaiterNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaiterNumberKeyTyped

        if (status == false) {
            txtWaiterNumber.setText("");
            status = true;
        }
        txtWaiterNumber.setForeground(Color.black);

    }//GEN-LAST:event_txtWaiterNumberKeyTyped

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped

        if (status == false) {
            txtPhoneNumber.setText("");
            status = true;
        }
        txtPhoneNumber.setForeground(Color.black);

    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtCnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnicKeyTyped

        if (status == false) {
            txtCnic.setText("");
            status = true;
        }
        txtCnic.setForeground(Color.black);

    }//GEN-LAST:event_txtCnicKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped

        if (status == false) {
            txtAddress.setText("");
            status = true;
        }
        txtAddress.setForeground(Color.black);


    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void txtFatherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFatherNameFocusLost
        status = false;
    }//GEN-LAST:event_txtFatherNameFocusLost

    private void txtPhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneNumberFocusLost
        status = false;
    }//GEN-LAST:event_txtPhoneNumberFocusLost

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        status = false;
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtWaiterNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWaiterNameFocusLost
        status = false;
    }//GEN-LAST:event_txtWaiterNameFocusLost

    private void txtWaiterNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWaiterNumberFocusLost
        status = false;
    }//GEN-LAST:event_txtWaiterNumberFocusLost

    private void txtCnicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnicFocusLost
        status = false;
    }//GEN-LAST:event_txtCnicFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbleWaiter;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCnic;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtWaiterName;
    private javax.swing.JTextField txtWaiterNumber;
    // End of variables declaration//GEN-END:variables
}
